### ISSUE TITLE
paradox-list-packages, stuck at "Loading"

### ISSUE THREAD

**Issue by kaushalmodi** [Malabarba/paradox#107]
Hi Artur,

I am back to emacs after a month's vacation away from my computer!

I updated all the packages (including paradox) [This update went well] and also to the latest commit on emacs-25 branch.

After all the updates, when I restart emacs and do `M-x paradox-list-packges`, the *Paradox Menu* buffer gets stuck at the below state even after waiting for quite few minutes (about 15-20).

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/11725730/2899a23a-9f49-11e5-850e-3ac1a88b3089.png)

If you have an idea what change in the last month in emacs or paradox could be causing this, let me know so that I can provide targeted debug info. 

Thanks!

**Comment by kaushalmodi** [comment]
At times, the *Paradox Menu* buffer stays empty while Loading is stuck and I see `(1/0)` instead of where `(3029/3029)` is in the above screenshot.

**Comment by sentorxx** [comment]
Same here `paradox-list-packages` doesn't load packages.

After killing the buffer and trying package-list-packages nothing occurs. After restarting emacs `package-list-packages` works `paradox-list-packages` not.

**Comment by Malabarba** [comment]
There was a macro problem a while ago. Make sure you're on the latest emacs-25 snapshot, then try  reinstalling paradox.

**Comment by Malabarba** [comment]
Oh, and welcome back @kaushalmodi :-)

**Comment by kaushalmodi** [comment]
@Malabarba Ah, I understand now. So the problem was that I **first updated paradox** using the older snapshot of emacs (then *master* branch as of Nov 12) and then updated the emacs snapshot (now *emacs-25* as of Dec 10). 

Let me try deleting and reinstalling paradox once I am at a PC. Will keep you posted.

**Comment by kaushalmodi** [comment]
The issue is fixed by reinstalling paradox while on the latest snapshot of emacs-25 branch. Thanks!

**Comment by Malabarba** [comment]
> Ah, I understand now. So the problem was that I first updated paradox using the older snapshot of emacs (then master branch as of Nov 12) and then updated the emacs snapshot (now emacs-25 as of Dec 10).

Indeed. Terribly subtle. :-(

**Comment by sentorxx** [comment]
Fixed here by getting fresh git sources from git://git.savannah.gnu.org/emacs.git. My emacs was about 2 month old.

**Comment by swarnendubiswas** [comment]
I am facing a similar problem, with Emacs built from git. Deleting all packages and reinstalling them does not solve the problem for me. Actually even `package-list-packages` seem to get stuck at "Loading" with version >= 25.1.50.x. Do you have any suggestions?

**Comment by crankyadmin** [comment]
@swarnendubiswas `M-x package-reinstall RET paradox RET` should fix your issue.

**Comment by jtecca** [comment]
Just came here to see if anyone else was having the same issue.  I'm running "25.0,.94.2" on Windows (here at work) and reinstalling paradox worked after having upgraded from 24->25 pretest.

Interestingly, I haven't had this issue at home (on Debian) though I suspect that paradox may have gotten reinstalled after I rebuilt the pretest from git.

**Comment by poulpoulsen** [comment]
hello,
i just install paradox on emacs 26 plattform win81 64bit.
Unfortunately terrible slow...
Cannot use it.

Regards
Poul
