### ISSUE TITLE
Star Count Issue 

### ISSUE THREAD

**Issue by sarvex** [Malabarba/paradox#66]
The paradox start count is not showing anymore; probably because of this [commit](https://github.com/Malabarba/paradox/commit/2a7231f2937f46fe161362d13175b63f0ee766c8)

**Comment by Malabarba** [comment]
Sorry, there was a typo in that commit. Could you check whether it's fixed now?

**Comment by sarvex** [comment]
Still unable to see the Stars

[Paradox] Error downloading Github data

**Comment by Malabarba** [comment]
Ok. Should be fixed now. Try updating from Melpa again.

**Comment by kaushalmodi** [comment]
I am seeing this problem too. I am on emacs 25.x with the latest paradox from Melpa.

**Comment by Malabarba** [comment]
@kaushalmodi I can't reproduce this on Emacs 25 anymore.
Are you on the latest Emacs? Or are you still waiting on that expand-region issue?

**Comment by kaushalmodi** [comment]
Yeah, still waiting on the save-excursion fix. Does this need your latest
edits in the master?

-- 
Kaushal Modi
On Apr 9, 2015 11:28 AM, "Artur Malabarba" <notifications@github.com> wrote:
>
> @kaushalmodi I can't reproduce this on Emacs 25 anymore.
> Are you on the latest Emacs? Or are you still waiting on that
expand-region issue?

**Comment by Malabarba** [comment]
Very possibly yes. Though I can't be sure without testing manually.

**Comment by kaushalmodi** [comment]
I am getting the same problem on the latest build from master as of today. I tried deleting the auto created url folder and pcache created var folder but that too didn't help.

**Comment by Malabarba** [comment]
@kaushalmodi I still haven't managed to reproduce this. I pushed a change which is slightly related, so try again and see if it changes.

I it's still happening:

1. Exactly what error/message do you get? And what happens in paradox afterwards?
2. Would you be willing to do some digging? If so:
    - You might get a backtrace if you do `M-x toggle-debug-on-error`.
    - Try setting `package-menu-async` to nil, see if anything changes.
    - You can try adding some `message` calls in `paradox--refresh-star-count` to find out what's going on.

**Comment by Malabarba** [comment]
No wait! I found the issue.

**Comment by kaushalmodi** [comment]
Cool! Thanks for finding it.

I have been on travel; otherwise I would have definitely helped you to
debug this.

**Comment by Malabarba** [comment]
No problem. Should be fixed on the next Melpa build. Enjoy your travels.

**Comment by kaushalmodi** [comment]
The issue is fixed for me. Thanks!
